name: matrix test on CI
on:
  push:
  workflow_dispatch:
jobs:
  deploy-job:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        images: [nginx]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Welcome to the docker details
        run: docker info

      - name: OS details of ${{ matrix.os }}
        run: docker run ${{ matrix.images }}